### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by heshlief** [sihwapark/topic-bubbles#1]
Hi I really admire this work so i tried it out but when i tried it it didnt load because it was asking for config.json file do you know which file is that

**Comment by gauravkoradiya** [comment]
same issue. I have data with 5 files stored at data folder and after when i try to run index.html at that time it not showing any error as well as visualization.

**Comment by sihwapark** [comment]
@heshlief @gauravkoradiya thank you for reporting the issue. I made an update that has `config.json` in the `data` folder as default. Actually, it should even work without `config.json` file but I made it work correctly by having the file. Also, please run all code on an http server. For running a local server on your computer, read [this](https://gist.github.com/jgravois/5e73b56fa7756fd00b89).

The purpose of `config.json` file is that by putting a path to the raw json files generated by dfrtopics, you can see the content of json documents when you click links in the top 20 documents view.

```
{
	"json_cache_path": "" // put a path to raw json files here
}
```
